name: Backend Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: cd backend && npm ci

    - name: Run linter
      run: cd backend && npm run lint

    - name: Run tests
      run: cd backend && npm test

    - name: Build
      run: cd backend && npm run build