name: iOS Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.2.1'
    
    - name: Install dependencies
      run: cd ios && pod install
      
    - name: Build
      run: xcodebuild -workspace ios/VCInvestmentDiscovery.xcworkspace -scheme VCInvestmentDiscovery -destination 'platform=iOS Simulator,name=iPhone 13' build
      
    - name: Run tests  
      run: xcodebuild -workspace ios/VCInvestmentDiscovery.xcworkspace -scheme VCInvestmentDiscovery -destination 'platform=iOS Simulator,name=iPhone 13' test